### ISSUE TITLE
Taiwan duplicate?

### ISSUE THREAD

**Issue by datapumpernickel** [meflynn/troopdata#4]
Hi,

thanks for the wonderful package and easy way of querying US military information. This is very useful. 
I noticed that for Taiwan in 2021 there is two entries with differing countrycodes (713 and 1012 respectively)
``` r
get_troopdata(startyear = 2021, endyear = 2021, host = "TWN")
```

I know that 713 is correct for TWN, but I am not sure where the 1012 comes from and whether the origin of the "error" affects other entries. 

All the best and thanks

**Comment by meflynn** [comment]
Thanks! I'm glad you're finding it useful.

39 is the correct number of personnel based on the September DMDC reports. This corresponds to the 1012 code. We used supplemental four digit codes for some cases where there weren't corresponding COW codes, but this is definitely an error. I probably won't fix it until the overhaul of the package, though, but I appreciate you flagging it. 

Looking over the code it appears to be an error limited to Taiwan's 2021 values. We used a slightly different method of updating the data with the 2021 values this time around which is probably why we didn't pick up on this sooner. But if you come across anything else please do let me know.

**Comment by datapumpernickel** [comment]
Thanks for getting back at this! Good to hear that you found the origin and it does not affect other countries!  
One more minor request, while I am at it. I know that technically the source data is probably all in the cited papers, but if you would provide the links to the original data in the readme that would be very convenient.
In this case it was: https://dwp.dmdc.osd.mil/dwp/app/dod-data-reports/workforce-reports right? 

Thanks, very much appreciate your time and work. Should I close or do you want to keep it open for your next overhaul-commit?

**Comment by meflynn** [comment]
Let's leave it open so I have an active bookmark for this. Otherwise I'll probably forget to double check. It will also help me to remember to add the link to the README file.
